#!/bin/bash

set -e

# Check if an existing stash exists whenever you checkout to a branch

PREVIOUS_HEAD_REF="$1"
NEW_HEAD_REF="$2"
CHECKOUT_WAS_A_BRANCH_FLAG="$3"

function act_on_stash_found() {
  echo ""
  echo -e "\033[0;31m[WARNING] Stash found saved from the branch you're checking into, maybe you already did some work here? \033[0m"
  echo ""
  echo "Let me do a 'git stash list' for you..."
  echo $(git stash list)
}

if [[ "$CHECKOUT_WAS_A_BRANCH_FLAG" == "1" ]]; then
  CURRENT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

  git stash list | cut -d ":" -f 2 | grep -qi $CURRENT_BRANCH_NAME && act_on_stash_found

fi
